module.exports = {
  ac: 'on',
  c: [
    'China',
    'Indonesia',
    'Russian Federation',
    'Brazil',
    'United States',
    'Venezuela',
    'Australia',
    'Korea, Republic of',
    'Japan',
    'Viet Nam',
    'Hong Kong',
    'Ukraine',
    'France',
    'Argentina',
    'Thailand',
    'Nepal',
    'Philippines',
    'Colombia',
    'Cambodia',
    'Georgia',
    'Afghanistan',
    'Bosnia and Herzegovina',
    'Taiwan',
    'Egypt',
    'Ecuador',
    'Hungary',
    'Poland',
    'Chile',
    'Taiwan',
    'United Arab Emirates',
    'India',
    'Germany',
    'Canada',
    'Slovakia',
    'Peru',
    'Sierra Leone'
  ],
  allPorts: 1,
  p: null,
  pr: [0, 1, 2],
  a: [0, 1, 2, 3, 4],
  pl: 'on',
  sp: [1, 2, 3],
  ct: [1, 2, 3],
  s: 0,
  o: 0,
  pp: 3,
  sortBy: 'date'
}